<a href="https://colab.research.google.com/github/Aqib-Ramzan-Butt/AI-Projects/blob/main/Next_Word_Prediction_with_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# **Sample Data for Training**

In [ ]:
sentences = [
    "Machine learning algorithms are powerful tools."
    "I enjoy exploring new algorithms."
    "Learning about AI is captivating."
    "Deep learning models can be complex."
    "I love understanding how neural networks work."
    "The field of data science is evolving rapidly."
    "I find artificial intelligence intriguing."
    "Studying computer vision is exciting."
    "Natural language processing is a fascinating domain."
    "I enjoy coding in Python for data science projects."
    "Building models is a creative process."
    "I love experimenting with different machine learning techniques."
    "The potential of AI to transform industries is amazing."
    "I enjoy staying updated with the latest tech trends."
    "Learning about reinforcement learning is interesting."
    "I find predictive modeling to be very useful."
    "I love solving problems with data analysis."
    "Data preprocessing is a crucial step in machine learning."
    "I enjoy reading research papers on deep learning."
    "I find optimization techniques fascinating."
    "Understanding algorithms helps in developing better solutions."
    "I love the challenge of debugging code."
    "Machine learning applications are diverse and impactful."
    "I enjoy collaborating with others on tech projects."
    "Learning new programming languages is fun."
    "I love working with large datasets."
    "I find feature engineering to be an art."
    "Model evaluation is an essential part of machine learning."
    "I enjoy attending tech conferences."
    "Learning about big data technologies is exciting."
    "I love experimenting with neural network architectures."
    "I find the theory behind machine learning algorithms interesting."
    "I enjoy visualizing data insights."
    "Machine learning models can make accurate predictions."
    "I love the creativity involved in data storytelling."
    "I find unsupervised learning techniques intriguing."
    "I enjoy automating tasks with AI."
    "Learning about AI ethics is important."
    "I love the problem-solving aspect of machine learning."
    "I find cloud computing technologies fascinating."
    "I enjoy using machine learning for real-world applications."
    "I love experimenting with different data preprocessing techniques."
    "I find transfer learning to be a powerful approach."
    "I enjoy working on machine learning projects."
    "Learning about data privacy is crucial."
    "I love the innovation happening in the AI field."
    "I find data visualization tools useful."
    "I enjoy testing and validating machine learning models."
    "I love discovering new machine learning applications."
    "I find ensemble methods to be effective."
    "I enjoy learning from data."
    "Machine learning can provide valuable insights."
    "I love the interdisciplinary nature of AI."
    "I find recommendation systems interesting."
    "I enjoy participating in hackathons."
    "Learning about neural networks is fascinating."
    "I love the potential of AI to solve complex problems."
    "I find sentiment analysis intriguing."
    "I enjoy implementing machine learning algorithms."
    "I love the excitement of discovering patterns in data."
    "I find time series analysis challenging."
    "I enjoy exploring different types of data."
    "Machine learning is transforming various industries."
    "I love working on predictive analytics."
    "I find anomaly detection to be useful."
    "I enjoy studying the mathematics behind machine learning."
    "I love the hands-on experience of building models."
    "I find clustering techniques interesting."
    "I enjoy exploring open-source machine learning libraries."
    "Machine learning can automate complex tasks."
    "I love the flexibility of machine learning models."
    "I find computer vision applications fascinating."
    "I enjoy solving real-world problems with AI."
    "I love the continuous learning aspect of AI."
    "I find reinforcement learning to be challenging."
    "I enjoy experimenting with hyperparameter tuning."
    "Machine learning can improve decision-making processes."
    "I love the creativity involved in feature selection."
    "I find generative models to be fascinating."
    "I enjoy reading about the latest AI advancements."
    "Machine learning can enhance user experiences."
    "I love the diversity of machine learning applications."
    "I find natural language generation intriguing."
    "I enjoy working with text data."
    "Machine learning can optimize business processes."
    "I love the innovation in AI research."
    "I find the concept of machine learning interpretability interesting."
    "I enjoy creating machine learning workflows."
    "Machine learning can uncover hidden patterns."
    "I love the impact of AI on society."
    "I find deep reinforcement learning fascinating."
    "I enjoy developing custom machine learning solutions."
    "Machine learning can improve customer experiences."
    "I love the potential of AI in healthcare."
    "I find the scalability of machine learning models intriguing."
    "I enjoy applying machine learning to finance."
    "Machine learning can enhance security measures."
    "I love the possibilities of AI in creative industries."
    "I find the ethical implications of AI important."
    "I enjoy sharing knowledge about machine learning."
    "This Free Advance AI Course that is helping alot of students to learn the concepts of AI and provides the detailed guideline on how to learn AI. This course enables the students to make their own projects. Updates them with the state of the art technologies and provide all the necessary knowlegde so that they should not be dependend on anyone to be able to learn anything."
]

In [ ]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

total_words = len(tokenizer.word_index) + 1
print(total_words)
print(tokenizer.word_index)

input_sequences = []

for line in sentences:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)




max_sequence_len = max([len(x) for x in input_sequences])

input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
print(input_sequences)


254
{'i': 1, 'learning': 2, 'machine': 3, 'the': 4, 'enjoy': 5, 'love': 6, 'find': 7, 'of': 8, 'ai': 9, 'is': 10, 'to': 11, 'data': 12, 'with': 13, 'in': 14, 'can': 15, 'be': 16, 'about': 17, 'models': 18, 'on': 19, 'fascinating': 20, 'algorithms': 21, 'intriguing': 22, 'techniques': 23, 'interesting': 24, 'applications': 25, 'a': 26, 'projects': 27, 'experimenting': 28, 'and': 29, 'working': 30, 'exploring': 31, 'new': 32, 'deep': 33, 'complex': 34, 'neural': 35, 'different': 36, 'potential': 37, 'industries': 38, 'tech': 39, 'reinforcement': 40, 'useful': 41, 'solving': 42, 'problems': 43, 'analysis': 44, 'technologies': 45, 'learn': 46, 'are': 47, 'powerful': 48, 'tools': 49, 'understanding': 50, 'how': 51, 'networks': 52, 'field': 53, 'science': 54, 'studying': 55, 'computer': 56, 'vision': 57, 'exciting': 58, 'natural': 59, 'language': 60, 'for': 61, 'building': 62, 'creative': 63, 'latest': 64, 'predictive': 65, 'preprocessing': 66, 'crucial': 67, 'reading': 68, 'research': 69, '

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, UpSampling2D, Concatenate
from tensorflow.keras.models import Model

# ... (Data loading and preprocessing)

def unet(input_size=(256, 256, 3)):
    inputs = tf.keras.Input(shape=input_size)

    # Encoder
    conv1 = Conv2D(64, 3, activation='relu', padding='same')(inputs)
    conv1 = Conv2D(64, 3, activation='relu', padding='same')(conv1)
    pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)

    # ... (Similar blocks for deeper layers)

    # Decoder
    up7 = UpSampling2D(size=(2, 2))(conv7)
    merge7 = Concatenate()([up7, conv6])
    conv7 = Conv2D(64, 3, activation='relu', padding='same')(merge7)
    conv7 = Conv2D(64, 3, activation='relu', padding='same')(conv7)

    # ... (Similar blocks for shallower layers)

    outputs = Conv2D(1, 1, activation='sigmoid')(conv1)

    model = Model(inputs=inputs, outputs=outputs)
    return model

# Compile and train the model
model.compile(optimizer='adam', loss='binary_crossentropy')
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val))

In [ ]:
X = input_sequences[:, :-1]
print("Input Data: ",X)

y = input_sequences[:, -1]
print("Labels: ",y)

y = tf.keras.utils.to_categorical(y, num_classes=total_words)

Input Data:  [[  0   0   0 ...   0   0   3]
 [  0   0   0 ...   0   3   2]
 [  0   0   0 ...   3   2  21]
 ...
 [  0   0   3 ...  11  16 252]
 [  0   3   2 ...  16 252  11]
 [  3   2  21 ... 252  11  46]]
Labels:  [  2  21  47  48  49   1   5  31  32  21   2  17   9  10  98  33   2  18
  15  16  34   1   6  50  51  35  52  99   4  53   8  12  54  10 100 101
   1   7 102 103  22  55  56  57  10  58  59  60 104  10  26  20 105   1
   5 106  14 107  61  12  54  27  62  18  10  26  63 108   1   6  28  13
  36   3   2  23   4  37   8   9  11 109  38  10 110   1   5 111 112  13
   4  64  39 113   2  17  40   2  10  24   1   7  65 114  11  16 115  41
   1   6  42  43  13  12  44  12  66  10  26  67 116  14   3   2   1   5
  68  69 117  19  33   2   1   7 118  23  20  50  21 119  14  70 120  71
   1   6   4 121   8 122 123   3   2  25  47 124  29 125   1   5 126  13
 127  19  39  27   2  32 128 129  10 130   1   6  30  13 131 132   1   7
  72 133  11  16  73  74 134 135  10  73 136 137   8   3

In [ ]:
model = Sequential([
    Embedding(total_words, 10, input_length=max_sequence_len-1),

    SimpleRNN(60),

    Dense(total_words, activation='softmax')
])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(X, y, epochs=50, verbose=1)

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 6s 117ms/step - accuracy: 0.0155 - loss: 5.4932
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 90ms/step - accuracy: 0.0388 - loss: 5.1328
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.0778 - loss: 4.7506
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.0948 - loss: 4.6702
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 70ms/step - accuracy: 0.1079 - loss: 4.6424
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - accuracy: 0.0995 - loss: 4.5594
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.0816 - loss: 4.6712
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.0969 - loss: 4.5752
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - accuracy: 0.0784 - loss: 4.6581
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.0808 - loss: 4.6246
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - accuracy: 0.0902 - loss: 4.5249
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - accuracy

# **Next Word Prediction:**

**Seed Text Conversion:** The input text (seed_text) is converted to a sequence of integers using the tokenizer.

**Padding:** The integer sequence is padded to ensure it matches the model's expected input length.

**Prediction:** The model predicts the probability of each word in the vocabulary as the next word.

**Selection and Update:** The word with the highest probability is selected, converted back to a word, and appended to the seed text.

**Iterative Prediction:** This process can be repeated for a specified number of words (next_words).

In [ ]:
def predict_next_word(seed_text, next_words=1):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]

        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

        predicted = model.predict(token_list, verbose=0)

        predicted_word_index = np.argmax(predicted, axis=-1)[0]

        predicted_word = tokenizer.index_word[predicted_word_index]

        seed_text += " " + predicted_word

    return seed_text


In [ ]:
print(predict_next_word("machine lEARNING can enhance"))

machine lEARNING can enhance decision
